# Generated by Django 5.2.1 on 2025-05-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_setup_complete',
            field=models.BooleanField(default=False, help_text='Indicates if the user has successfully verified their MFA setup.'),
        ),
    ]
