# Generated by Django 5.2.3 on 2025-06-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mfa_enabled',
            new_name='phone_number_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mfa_secret',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mfa_setup_complete',
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_email_enabled',
            field=models.BooleanField(default=False, help_text='Is MFA via Email OTP enabled?'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_otp',
            field=models.CharField(blank=True, help_text='Stores the hashed one-time password.', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_otp_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiry time for the one-time password.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_sms_enabled',
            field=models.BooleanField(default=False, help_text='Is MFA via SMS OTP enabled?'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_totp_secret',
            field=models.CharField(blank=True, help_text='Secret for Time-based One-Time Password (TOTP).', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_totp_setup_complete',
            field=models.BooleanField(default=False, help_text='Indicates if the user has successfully verified their TOTP setup.'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
