# Generated by Django 5.2.3 on 2025-06-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_otp_purpose',
            field=models.CharField(blank=True, help_text="Purpose of the OTP (e.g., 'phone_verification', 'mfa_setup').", max_length=50, null=True),
        ),
    ]
