# Generated by Django 5.2.2 on 2025-06-25 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_mfa_otp_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Email address used in attempt', max_length=254, null=True)),
                ('attempt_type', models.CharField(choices=[('login', 'Login'), ('social_login', 'Social Login'), ('password_reset', 'Password Reset'), ('mfa_verification', 'MFA Verification'), ('registration', 'Registration')], default='login', max_length=20)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the attempt')),
                ('user_agent', models.TextField(help_text='User agent string')),
                ('success', models.BooleanField(help_text='Whether the attempt was successful')),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failure if unsuccessful', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(blank=True, help_text='Social auth provider (if applicable)', max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the attempt')),
                ('user', models.ForeignKey(blank=True, help_text='User associated with the attempt (if known)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'authentication attempt',
                'verbose_name_plural': 'authentication attempts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email', 'timestamp'], name='users_authe_email_abbaa1_idx'), models.Index(fields=['ip_address', 'timestamp'], name='users_authe_ip_addr_e8e4d7_idx'), models.Index(fields=['attempt_type', 'timestamp'], name='users_authe_attempt_b09815_idx'), models.Index(fields=['success', 'timestamp'], name='users_authe_success_5fab85_idx')],
            },
        ),
    ]
