# Generated by Django 5.2.2 on 2025-06-25 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_authentication_attempt_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jti', models.CharField(help_text='JWT ID (jti) claim', max_length=255, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(help_text='Reason for blacklisting', max_length=255)),
                ('expires_at', models.DateTimeField(help_text='When the original token would have expired')),
                ('user', models.ForeignKey(help_text='User who owned the token', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'blacklisted token',
                'verbose_name_plural': 'blacklisted tokens',
                'ordering': ['-blacklisted_at'],
                'indexes': [models.Index(fields=['token_jti'], name='users_black_token_j_3fde1a_idx'), models.Index(fields=['user', 'blacklisted_at'], name='users_black_user_id_c1b358_idx'), models.Index(fields=['expires_at'], name='users_black_expires_5cdd99_idx')],
            },
        ),
    ]
