# Generated by Django 5.2.3 on 2025-07-17 20:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_increase_refresh_token_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredClient',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique client identifier', primary_key=True, serialize=False)),
                ('client_name', models.CharField(help_text='Human-readable client name', max_length=100)),
                ('client_type', models.CharField(choices=[('PATIENT_WEB', 'Patient Web Application (Waridi)'), ('PATIENT_MOBILE', 'Patient Mobile Application (Afyaflow Mobile)'), ('PROVIDER_WEB', 'Provider Web Application'), ('PROVIDER_MOBILE', 'Provider Mobile Application'), ('ADMIN_WEB', 'Admin Web Application')], help_text='Type of client application', max_length=20)),
                ('allowed_domains', models.JSONField(default=list, help_text='List of allowed domains for this client')),
                ('api_key_hash', models.CharField(help_text='Hashed API key for client authentication', max_length=255)),
                ('signing_key', models.TextField(help_text='Unique JWT signing key for this client')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this client is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_requests_per_minute', models.IntegerField(default=60, help_text='Rate limit for this client')),
                ('token_lifetime_access', models.IntegerField(default=60, help_text='Access token lifetime in minutes')),
                ('token_lifetime_refresh', models.IntegerField(default=10080, help_text='Refresh token lifetime in minutes')),
                ('require_device_fingerprint', models.BooleanField(default=False, help_text='Whether device fingerprinting is required')),
                ('allow_social_login', models.BooleanField(default=True, help_text='Whether social login is allowed for this client')),
                ('require_totp', models.BooleanField(default=False, help_text='Whether TOTP is required for this client')),
                ('enhanced_monitoring', models.BooleanField(default=False, help_text='Whether enhanced security monitoring is enabled')),
            ],
            options={
                'verbose_name': 'registered client',
                'verbose_name_plural': 'registered clients',
                'ordering': ['client_name'],
                'indexes': [models.Index(fields=['client_type'], name='users_regis_client__8cecc2_idx'), models.Index(fields=['is_active'], name='users_regis_is_acti_10f5dd_idx'), models.Index(fields=['created_at'], name='users_regis_created_a11a04_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PATIENT', 'Patient'), ('PROVIDER', 'Provider'), ('ADMIN', 'Admin')], help_text='Role name (PATIENT, PROVIDER, ADMIN)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the role and its permissions')),
                ('permissions', models.JSONField(default=list, help_text='List of permissions associated with this role')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user role',
                'verbose_name_plural': 'user roles',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='users_userr_name_1e79c2_idx'), models.Index(fields=['is_active'], name='users_userr_is_acti_e1ec1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the role was assigned')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role assignment is currently active')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this role assignment expires (optional)', null=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who made this role assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Role assigned to the user', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='users.userrole')),
                ('user', models.ForeignKey(help_text='User assigned to this role', on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user role assignment',
                'verbose_name_plural': 'user role assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['user', 'role'], name='users_userr_user_id_59e25d_idx'), models.Index(fields=['user', 'is_active'], name='users_userr_user_id_44802a_idx'), models.Index(fields=['role', 'is_active'], name='users_userr_role_id_f5d3c6_idx'), models.Index(fields=['assigned_at'], name='users_userr_assigne_9ba7a4_idx'), models.Index(fields=['expires_at'], name='users_userr_expires_dec903_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'role'), name='unique_active_user_role')],
            },
        ),
    ]
