# Generated by Django 5.2.3 on 2025-07-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_fix_security_context_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('provider', 'Provider'), ('patient', 'Patient'), ('operations', 'Operations')], default='provider', help_text='User type for gateway authentication (provider, patient, operations)', max_length=20),
        ),
    ]
