# Generated by Django 5.2.3 on 2025-07-17 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_role_and_client_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationattempt',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client application used for this attempt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authentication_attempts', to='users.registeredclient'),
        ),
        migrations.AddField(
            model_name='authenticationattempt',
            name='client_type',
            field=models.CharField(blank=True, help_text='Type of client application', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='authenticationattempt',
            name='role_attempted',
            field=models.CharField(blank=True, help_text='Role that was being authenticated for', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='authenticationattempt',
            name='security_context',
            field=models.JSONField(blank=True, default=dict, help_text='Additional security context and metadata'),
        ),
        migrations.AddField(
            model_name='blacklistedtoken',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client application that issued this token', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklisted_tokens', to='users.registeredclient'),
        ),
        migrations.AddField(
            model_name='blacklistedtoken',
            name='client_type',
            field=models.CharField(blank=True, help_text='Type of client application', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blacklistedtoken',
            name='violation_reason',
            field=models.CharField(blank=True, help_text='Specific security violation that caused blacklisting', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client application that issued this token', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='users.registeredclient'),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='client_type',
            field=models.CharField(blank=True, help_text='Type of client application', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='device_fingerprint',
            field=models.CharField(blank=True, help_text='Device fingerprint for security tracking', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='device_trust_enabled',
            field=models.BooleanField(default=False, help_text='Whether device trust is enabled for extended sessions'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_passwordless',
            field=models.BooleanField(default=False, help_text='Whether this user uses passwordless authentication (patients)'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_security_check',
            field=models.DateTimeField(blank=True, help_text='Last time security policies were checked for this user', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_role',
            field=models.ForeignKey(blank=True, help_text='Primary role for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='users.userrole'),
        ),
        migrations.AddIndex(
            model_name='authenticationattempt',
            index=models.Index(fields=['client', 'timestamp'], name='users_authe_client__b05633_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationattempt',
            index=models.Index(fields=['client_type', 'timestamp'], name='users_authe_client__d2ed97_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationattempt',
            index=models.Index(fields=['role_attempted', 'timestamp'], name='users_authe_role_at_efe5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['client', 'blacklisted_at'], name='users_black_client__0c27d2_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['client_type'], name='users_black_client__91d423_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['user', 'client'], name='users_refre_user_id_f29cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['client_type'], name='users_refre_client__b96333_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['expires_at'], name='users_refre_expires_cdd00d_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['is_revoked'], name='users_refre_is_revo_328d7d_idx'),
        ),
    ]
