# Generated by Django 5.2.3 on 2025-07-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_operations_role_and_gateway_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organizationcontext',
            index=models.Index(fields=['organization_id'], name='users_organ_organiz_87bea3_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcontext',
            index=models.Index(fields=['branch_id'], name='users_organ_branch__ba93db_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcontext',
            index=models.Index(fields=['cluster_id'], name='users_organ_cluster_e12a97_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcontext',
            index=models.Index(fields=['is_active'], name='users_organ_is_acti_507daa_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcontext',
            index=models.Index(fields=['created_at'], name='users_organ_created_a03c49_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceaccount',
            index=models.Index(fields=['service_id'], name='users_servi_service_51e669_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceaccount',
            index=models.Index(fields=['service_type'], name='users_servi_service_74b3ee_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceaccount',
            index=models.Index(fields=['is_active'], name='users_servi_is_acti_6dc127_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceaccount',
            index=models.Index(fields=['created_at'], name='users_servi_created_4da095_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationcontext',
            constraint=models.UniqueConstraint(fields=('organization_id', 'branch_id', 'cluster_id'), name='unique_org_branch_cluster'),
        ),
    ]
