# Generated by Django 5.0.6 on 2024-07-28 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('provider', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField()),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Authentication Attempt',
                'verbose_name_plural': 'Authentication Attempts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text="The name of the social provider (e.g., 'google', 'microsoft').", max_length=50)),
                ('provider_id', models.CharField(help_text="The unique identifier for the user on the provider's platform.", max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('access_token', models.TextField(blank=True, help_text='Encrypted access token from the provider.', null=True)),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted refresh token from the provider.', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='The expiry time of the access token.', null=True)),
                ('extra_data', models.JSONField(default=dict, help_text='Provider-specific profile data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'indexes': [models.Index(fields=['user', 'provider'], name='user_provider_idx'), models.Index(fields=['provider', 'provider_id'], name='provider_user_id_idx')],
                'unique_together': {('provider', 'provider_id')},
            },
        ),
    ]
